modification_author_id cannot be null
symphonists/xmlimporter pull request #54
Opened 2018-05-11 13:19 UTC by jude86-7

'Symphony Fatal Database Error: Column 'modification_author_id' cannot
be null' #53

2018-05-18 15:53 UTC, nitriques requested changes

2018-05-18 15:53 UTC, nitriques commented on lib/class.xmlimporter.php
> +					$entry->set('modification_author_id', is_null(Symphony::Engine()->Author()) ? '1' : Symphony::Engine()->Author()->get('id'));
Author is a static property, so the line should be

```php
$entry->set('modification_author_id', !Symphony::Author() ? '1' : Symphony::Author()->get('id'));
```

2018-05-20 14:59 UTC, jude86-7 commented
Many thanks, I've updated the request to show the amended code.

2018-06-01 20:35 UTC, nitriques approved these changes

2018-06-01 20:35 UTC, merged

2018-06-01 20:38 UTC, nitriques commented
Released as 3.0.1